bot:
  # Signal Bot Configuration
  signal_service: "signal-api:8080"
  phone_number: "+1234567890"  # Replace with your number

  # storage:
  #   redis_host: "redis"
  #   redis_port: 6379
commands:
  - name: ping
    contacts:
      - "+1234567890"  # Replace with your number
    groups: true  # Read from all groups
  - name: timeslots
    contacts:
      - "+1234567890"  # Replace with your number
    groups: true  # Read from all groups
  - name: book
    contacts:
      - "+1234567890"  # Replace with your number
    groups: true  # Read from all groups
  - name: aliases
    contacts:
      - "+1234567890"  # Replace with your number
    groups: true  # Read from all groups

usc:
  # Booking members with their credentials
  bookingMembers:
    - username: "your_username1"
      password: "your_password1"
    - username: "your_username2"
      password: "your_password2"
    # Add more booking members as needed

  # Aliases map friendly names to email addresses
  aliases:
    alex: "alex@gmail.com"
    bob: "bob@example.com"
    # Add more aliases as needed
